persistance.xml: Add a commented out example of how to add listeners   (doesn't work with our old version of Hibernate ejb support)
GuidNotFoundException: Make public so we can throw the same exception
  in PostingBoardBean as we do in EJBUtil.

PostingBoardBean: throw GuidNotFoundException when the user doesn't
  have access to the bean, instead of incosistently returning null.

PostingBoardBean: Call IndexWriter.close() ... otherwise we lose
  parts of the index. Add explicit index addition for new posts,
  since we can't rely on listeners. (And also potentially 
  allows a lot of optimization and robustification that we couldn't 
  do relying on the standard listeners)

find.jsp: Fix a broken JSP comment